const express = require('express');
const authRoutes = require('./authRoutes');
const appointmentRoutes = require('./appointmentRoutes');
const familyMemberRoutes = require('./familyMemberRoutes');
const doctorRoutes = require('./doctorRoutes');
const receptionistRoutes = require('./receptionistRoutes');
const medicalRoutes = require('./medicalRoutes');
const notificationRoutes = require('./notificationRoutes');
const billRoutes = require('./billRoutes');
const liveQueueRoutes = require('./liveQueueRoutes');
const publicRoutes = require('./publicRoutes');
const reportRoutes = require('./reportRoutes');
const patientRecordRoutes = require('./patientRecordRoutes');
const previousManualPatientRoutes = require('./previousManualPatientRoutes');
const opsRoutes = require('./opsRoutes');
const whatsappRoutes = require('./whatsappRoutes');
const whatsappMockRoutes = require('./whatsappMockRoutes');
const webhookRoutes = require('./webhookRoutes');

const router = express.Router();

router.use('/auth', authRoutes);
router.use('/appointments', appointmentRoutes);
router.use('/family-members', familyMemberRoutes);
router.use('/doctors', doctorRoutes);
router.use('/receptionist', receptionistRoutes);
router.use('/medical', medicalRoutes);
router.use('/notifications', notificationRoutes);
router.use('/bills', billRoutes);
router.use('/live-queue', liveQueueRoutes);
router.use('/public', publicRoutes);
router.use('/reports', reportRoutes);
router.use('/patient-records', patientRecordRoutes);
router.use('/previous-patients', previousManualPatientRoutes);
router.use('/ops', opsRoutes);
router.use('/whatsapp/mock', whatsappMockRoutes);
router.use('/whatsapp', whatsappRoutes);
router.use('/webhooks', webhookRoutes);

module.exports = router;
