-- Master products (master lab test prices) import SQL
-- Note: file is tab-separated UTF-8 text.

CREATE TABLE IF NOT EXISTS master_lab_test_prices (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  source_serial_no INT NULL,
  test_name VARCHAR(255) NOT NULL,
  sample_call VARCHAR(100) NULL,
  amount DECIMAL(10,2) NULL,
  test_type VARCHAR(150) NOT NULL,
  normalized_test_name VARCHAR(255) NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_lab_test_name_type (normalized_test_name, test_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


INSERT IGNORE INTO master_lab_test_prices 
  (source_serial_no, test_name, sample_call, amount, test_type, normalized_test_name) 
VALUES
  (1, 'Blood Group', 'EDTA', 100.00, 'SINGLE COMMON TEST', 'blood group'),
  (2, 'CBC', 'EDTA', 300.00, 'SINGLE COMMON TEST', 'cbc'),
  (3, 'Creatinine', 'SERUM', 450.00, 'SINGLE COMMON TEST', 'creatinine'),
  (4, 'CRP', 'SERUM', 450.00, 'SINGLE COMMON TEST', 'crp'),
  (5, 'CALCIUM', 'SERUM', 200.00, 'SINGLE COMMON TEST', 'calcium'),
  (6, 'ESR', 'EDTA', 100.00, 'SINGLE COMMON TEST', 'esr'),
  (7, 'Glucose Fasting', 'FLORIDE', 100.00, 'SINGLE COMMON TEST', 'glucose fasting'),
  (8, 'Glucose Postprandial', 'FLORIDE', 100.00, 'SINGLE COMMON TEST', 'glucose postprandial'),
  (9, 'Glucose Random', 'SERUM', 100.00, 'SINGLE COMMON TEST', 'glucose random'),
  (10, 'RA Factor', 'SERUM', 500.00, 'SINGLE COMMON TEST', 'ra factor'),
  (11, 'LFT', 'SERUM', 450.00, 'SINGLE COMMON TEST', 'lft'),
  (12, 'KFT', 'SERUM', 450.00, 'SINGLE COMMON TEST', 'kft'),
  (13, 'Lipid Profile', 'SERUM', 450.00, 'SINGLE COMMON TEST', 'lipid profile'),
  (14, 'T3, T4, TSH', 'SERUM', 450.00, 'SINGLE COMMON TEST', 't3, t4, tsh'),
  (15, 'Lipage', 'SERUM', 400.00, 'SINGLE COMMON TEST', 'lipage'),
  (16, 'SGOT', 'SERUM', NULL, 'SINGLE COMMON TEST', 'sgot'),
  (17, 'SGPT', 'SERUM', NULL, 'SINGLE COMMON TEST', 'sgpt'),
  (18, 'HBA1C', 'EDTA', 450.00, 'SINGLE COMMON TEST', 'hba1c'),
  (19, 'Uric Acid', 'SERUM', 200.00, 'SINGLE COMMON TEST', 'uric acid'),
  (20, 'Urine R/M', 'URINE', 100.00, 'SINGLE COMMON TEST', 'urine r/m'),
  (21, 'CRP', 'SERUM', 400.00, 'SINGLE COMMON TEST', 'crp'),
  (22, 'Vit B12', 'SERUM', 500.00, 'SINGLE COMMON TEST', 'vit b12'),
  (23, 'Vit D', 'SERUM', 600.00, 'SINGLE COMMON TEST', 'vit d'),
  (24, 'Amylase', 'SERUM', NULL, 'SINGLE COMMON TEST', 'amylase'),
  (25, 'Anti-ccp', 'SERUM', NULL, 'SINGLE COMMON TEST', 'anti-ccp'),
  (26, 'Beta-HCG', 'SERUM', NULL, 'SINGLE COMMON TEST', 'beta-hcg'),
  (27, 'CA125', 'SERUM', 900.00, 'SINGLE COMMON TEST', 'ca125'),
  (28, 'CA19.9', 'SERUM', NULL, 'SINGLE COMMON TEST', 'ca19.9'),
  (29, 'Estradiol E2', 'SERUM', NULL, 'SINGLE COMMON TEST', 'estradiol e2'),
  (30, 'HLAB-B27', 'EDTA', NULL, 'SINGLE COMMON TEST', 'hlab-b27'),
  (31, 'HB Electrophoresis', 'SERUM', 900.00, 'SINGLE COMMON TEST', 'hb electrophoresis'),
  (32, 'Herpis- H.S.V 12 2 IGG', 'SERUM', NULL, 'SINGLE COMMON TEST', 'herpis- h.s.v 12 2 igg'),
  (33, 'HBV DNA', 'SERUM', NULL, 'SINGLE COMMON TEST', 'hbv dna'),
  (34, 'HBV Viral Load', 'SERUM', NULL, 'SINGLE COMMON TEST', 'hbv viral load'),
  (35, 'Lron Profile', 'SERUM', NULL, 'SINGLE COMMON TEST', 'lron profile'),
  (36, 'LH', 'SERUM', 400.00, 'SINGLE COMMON TEST', 'lh'),
  (37, 'MP (Maleria)', 'SERUM', NULL, 'SINGLE COMMON TEST', 'mp (maleria)'),
  (38, 'PSA Total', 'SERUM', 650.00, 'SINGLE COMMON TEST', 'psa total'),
  (39, 'Serum IGE Total', 'SERUM', NULL, 'SINGLE COMMON TEST', 'serum ige total'),
  (40, 'Sickling', 'EDTA', 300.00, 'SINGLE COMMON TEST', 'sickling'),
  (41, 'TFT', 'SERUM', 450.00, 'SINGLE COMMON TEST', 'tft'),
  (42, 'Tissue Transglutaminase', 'SERUM', NULL, 'SINGLE COMMON TEST', 'tissue transglutaminase'),
  (43, 'Urine Culture', NULL, 500.00, 'SINGLE COMMON TEST', 'urine culture'),
  (44, 'Viral Markcr', 'SERUM', 1400.00, 'SINGLE COMMON TEST', 'viral markcr'),
  (45, 'Widal', 'EDTA', 200.00, 'SINGLE COMMON TEST', 'widal'),
  (46, 'Basic Arthritis Care (BAC)', 'SERUM', NULL, 'SINGLE COMMON TEST', 'basic arthritis care (bac)'),
  (1, 'AMH', 'SERUM', 1600.00, 'Hormonal Test', 'amh'),
  (2, 'Prolactin', 'SERUM', 400.00, 'Hormonal Test', 'prolactin'),
  (3, 'ANA', 'SERUM', NULL, 'Hormonal Test', 'ana'),
  (4, 'FSH', 'SERUM', 400.00, 'Hormonal Test', 'fsh'),
  (5, 'GH', 'SERUM', 400.00, 'Hormonal Test', 'gh'),
  (6, 'Testosterone', 'SERUM', 600.00, 'Hormonal Test', 'testosterone'),
  (7, 'Progesterone', 'SERUM', 650.00, 'Hormonal Test', 'progesterone'),
  (1, 'TB Gold', 'GREEN TUBE', 2000.00, 'SPECIAL TEST', 'tb gold'),
  (2, 'HCV', NULL, NULL, 'SPECIAL TEST', 'hcv'),
  (3, 'HBsAg', NULL, NULL, 'SPECIAL TEST', 'hbsag'),
  (4, 'HIV 1.2', NULL, NULL, 'SPECIAL TEST', 'hiv 1.2'),
  (5, 'HIV AB/AG', NULL, NULL, 'SPECIAL TEST', 'hiv ab/ag'),
  (6, 'Dengue', 'SERUM', 900.00, 'SPECIAL TEST', 'dengue'),
  (7, 'ELISA ANA', NULL, NULL, 'SPECIAL TEST', 'elisa ana'),
  (8, 'HPLC Precentage(Sickling)', 'EDTA', 100.00, 'SPECIAL TEST', 'hplc precentage(sickling)'),
  (9, 'Ferritin', 'SERUM', 750.00, 'SPECIAL TEST', 'ferritin'),
  (10, 'PSA Totel', 'SERUM', 700.00, 'SPECIAL TEST', 'psa totel'),
  (11, 'ACCP', 'SERUM', 900.00, 'SPECIAL TEST', 'accp'),
  (12, 'Hepetities', 'EDTA', 3200.00, 'SPECIAL TEST', 'hepetities');