ALTER TABLE master_users
  ADD COLUMN ward_no VARCHAR(50) NULL AFTER address,
  ADD COLUMN vidhan_sabha VARCHAR(150) NULL AFTER ward_no;

CREATE TABLE IF NOT EXISTS tbl_patient_clinical_documents (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  patient_id BIGINT(20) UNSIGNED NOT NULL,
  family_member_id BIGINT(20) UNSIGNED DEFAULT NULL,
  appointment_id BIGINT(20) UNSIGNED DEFAULT NULL,
  consultation_id BIGINT(20) UNSIGNED DEFAULT NULL,
  bill_id BIGINT(20) UNSIGNED DEFAULT NULL,
  fk_branch_id BIGINT(20) UNSIGNED NOT NULL,
  doctor_id BIGINT(20) UNSIGNED DEFAULT NULL,
  document_type VARCHAR(40) NOT NULL,
  title VARCHAR(150) NOT NULL,
  description VARCHAR(500) DEFAULT NULL,
  original_filename VARCHAR(255) NOT NULL,
  storage_driver VARCHAR(40) NOT NULL DEFAULT 'local_private',
  storage_key VARCHAR(500) NOT NULL,
  mime_type VARCHAR(120) NOT NULL,
  file_size BIGINT(20) UNSIGNED NOT NULL,
  checksum_sha256 CHAR(64) DEFAULT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  archived_at TIMESTAMP NULL DEFAULT NULL,
  archived_by BIGINT(20) UNSIGNED DEFAULT NULL,
  archive_reason VARCHAR(255) DEFAULT NULL,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  deleted_by BIGINT(20) UNSIGNED DEFAULT NULL,
  delete_reason VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by BIGINT(20) UNSIGNED DEFAULT NULL,
  updated_by BIGINT(20) UNSIGNED DEFAULT NULL,
  created_ip VARCHAR(64) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_patient_clinical_documents_patient (patient_id, family_member_id, status, created_at),
  KEY idx_patient_clinical_documents_branch (fk_branch_id, status, created_at),
  KEY idx_patient_clinical_documents_type (document_type, status, created_at),
  KEY idx_patient_clinical_documents_appointment (appointment_id),
  KEY idx_patient_clinical_documents_consultation (consultation_id),
  KEY idx_patient_clinical_documents_bill (bill_id),
  CONSTRAINT fk_patient_clinical_documents_patient FOREIGN KEY (patient_id) REFERENCES master_users (id),
  CONSTRAINT fk_patient_clinical_documents_family FOREIGN KEY (family_member_id) REFERENCES tbl_patient_family_members (id),
  CONSTRAINT fk_patient_clinical_documents_appointment FOREIGN KEY (appointment_id) REFERENCES tbl_appointments (appointment_id),
  CONSTRAINT fk_patient_clinical_documents_consultation FOREIGN KEY (consultation_id) REFERENCES tbl_consultations (id),
  CONSTRAINT fk_patient_clinical_documents_bill FOREIGN KEY (bill_id) REFERENCES tbl_bills (id),
  CONSTRAINT fk_patient_clinical_documents_branch FOREIGN KEY (fk_branch_id) REFERENCES master_clinic_branches (id),
  CONSTRAINT fk_patient_clinical_documents_doctor FOREIGN KEY (doctor_id) REFERENCES master_users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS log_patient_clinical_document_access (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  document_id BIGINT(20) UNSIGNED NOT NULL,
  patient_id BIGINT(20) UNSIGNED NOT NULL,
  family_member_id BIGINT(20) UNSIGNED DEFAULT NULL,
  fk_branch_id BIGINT(20) UNSIGNED NOT NULL,
  action VARCHAR(30) NOT NULL,
  actor_user_id BIGINT(20) UNSIGNED DEFAULT NULL,
  actor_role VARCHAR(20) DEFAULT NULL,
  ip_address VARCHAR(64) DEFAULT NULL,
  user_agent VARCHAR(255) DEFAULT NULL,
  metadata_json JSON DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_clinical_document_access_document (document_id, created_at),
  KEY idx_clinical_document_access_patient (patient_id, family_member_id, created_at),
  KEY idx_clinical_document_access_branch (fk_branch_id, created_at),
  CONSTRAINT fk_clinical_document_access_document FOREIGN KEY (document_id) REFERENCES tbl_patient_clinical_documents (id),
  CONSTRAINT fk_clinical_document_access_patient FOREIGN KEY (patient_id) REFERENCES master_users (id),
  CONSTRAINT fk_clinical_document_access_family FOREIGN KEY (family_member_id) REFERENCES tbl_patient_family_members (id),
  CONSTRAINT fk_clinical_document_access_branch FOREIGN KEY (fk_branch_id) REFERENCES master_clinic_branches (id),
  CONSTRAINT fk_clinical_document_access_actor FOREIGN KEY (actor_user_id) REFERENCES master_users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
