ALTER TABLE tbl_consultations
  MODIFY COLUMN workflow_status ENUM(
    'DRAFT',
    'READY_FOR_RECEPTION',
    'APPROVED_BY_RECEPTION',
    'REJECTED_BY_RECEPTION',
    'READY_FOR_MEDICAL',
    'PROCESSED_BY_MEDICAL',
    'COMPLETED_NO_PRESCRIPTION'
  ) NOT NULL DEFAULT 'DRAFT';
